default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: pbs_sensor_dev
  user: pbs_sensor_dev
  password:

test:
  <<: *default
  database: pbs_sensor_test
  user: pbs_sensor_test
  password:

production:
  <<: *default
