# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8f290ebe60cc0be31876642cc2fd0d2fd02083723e2c3e66607db26ba07028190a63d9a31bb7c0dc31582fd6ecdb1c57ae5ff2c6f6d5f52ec2645f0a10906fe

test:
  secret_key_base: 7a19f2c65bc9b83746b139a0a35281abd1532f15e4f6fd3bd673e7d8677a7e494f5d1bc3fc198e8637fbea8f261f6a08dfb6e7edcb8167a2ebed937e0ef73165

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
